-- ======================================================================
-- Schema — restore this FIRST, then 02-data.sql
--
-- Generated by Polsia from your app database.
-- Source PostgreSQL : 16.15 (ef25dd3)
-- Source schema     : public
-- Snapshot taken at : 2026-09-08 19:17:40.627251+00
--
-- FOREIGN KEYS ARE NOT IN THIS FILE. They are at the end of 02-data.sql,
-- after the rows, so the data can load in any order.
-- ======================================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET DateStyle = 'ISO, MDY';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';
SET search_path TO public;

CREATE TYPE "CheckoutOrderStatus" AS ENUM (
    'PENDING',
    'PAID'
);
CREATE TABLE "Address" (
    id text NOT NULL,
    "userId" text NOT NULL,
    name text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    zip text NOT NULL,
    country text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "CheckoutOrder" (
    id text NOT NULL,
    "stripeSessionId" text,
    status "CheckoutOrderStatus" NOT NULL,
    "totalCents" integer NOT NULL,
    "lineItems" jsonb NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "paidAt" timestamp(3) without time zone,
    "userId" text
);
CREATE TABLE "DigitalPurchase" (
    id text NOT NULL,
    "userId" text NOT NULL,
    "productId" text NOT NULL,
    "acquiredAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "StorefrontEvent" (
    id text NOT NULL,
    "eventName" text NOT NULL,
    source text NOT NULL,
    "productId" text,
    "createdAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "WaitlistEntry" (
    id text NOT NULL,
    email text NOT NULL,
    source text,
    "createdAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE account (
    id text NOT NULL,
    "accountId" text NOT NULL,
    "providerId" text NOT NULL,
    "userId" text NOT NULL,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" timestamp(3) without time zone,
    "refreshTokenExpiresAt" timestamp(3) without time zone,
    scope text,
    password text,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE contact_message (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    message text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE session (
    id text NOT NULL,
    "expiresAt" timestamp(3) without time zone NOT NULL,
    token text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "ipAddress" text,
    "userAgent" text,
    "impersonatedBy" text,
    "userId" text NOT NULL
);
CREATE TABLE "user" (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    "emailVerified" boolean NOT NULL,
    image text,
    role text,
    banned boolean,
    "banReason" text,
    "banExpires" timestamp(3) without time zone,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE verification (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    "expiresAt" timestamp(3) without time zone NOT NULL,
    "createdAt" timestamp(3) without time zone,
    "updatedAt" timestamp(3) without time zone
);
ALTER TABLE "Address" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "CheckoutOrder" ALTER COLUMN status SET DEFAULT 'PENDING'::"CheckoutOrderStatus";
ALTER TABLE "CheckoutOrder" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DigitalPurchase" ALTER COLUMN "acquiredAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "StorefrontEvent" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "WaitlistEntry" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE contact_message ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "user" ALTER COLUMN role SET DEFAULT 'user'::text;
ALTER TABLE "user" ALTER COLUMN banned SET DEFAULT false;
ALTER TABLE "Address" ADD CONSTRAINT "Address_pkey" PRIMARY KEY (id);
ALTER TABLE "CheckoutOrder" ADD CONSTRAINT "CheckoutOrder_pkey" PRIMARY KEY (id);
ALTER TABLE "DigitalPurchase" ADD CONSTRAINT "DigitalPurchase_pkey" PRIMARY KEY (id);
ALTER TABLE "StorefrontEvent" ADD CONSTRAINT "StorefrontEvent_pkey" PRIMARY KEY (id);
ALTER TABLE "WaitlistEntry" ADD CONSTRAINT "WaitlistEntry_pkey" PRIMARY KEY (id);
ALTER TABLE account ADD CONSTRAINT account_pkey PRIMARY KEY (id);
ALTER TABLE contact_message ADD CONSTRAINT contact_message_pkey PRIMARY KEY (id);
ALTER TABLE session ADD CONSTRAINT session_pkey PRIMARY KEY (id);
ALTER TABLE "user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);
ALTER TABLE verification ADD CONSTRAINT verification_pkey PRIMARY KEY (id);
CREATE INDEX "Address_userId_createdAt_idx" ON "Address" USING btree ("userId", "createdAt");
CREATE UNIQUE INDEX "CheckoutOrder_stripeSessionId_key" ON "CheckoutOrder" USING btree ("stripeSessionId");
CREATE INDEX "CheckoutOrder_userId_createdAt_idx" ON "CheckoutOrder" USING btree ("userId", "createdAt");
CREATE INDEX "DigitalPurchase_userId_acquiredAt_idx" ON "DigitalPurchase" USING btree ("userId", "acquiredAt");
CREATE UNIQUE INDEX "DigitalPurchase_userId_productId_key" ON "DigitalPurchase" USING btree ("userId", "productId");
CREATE INDEX "StorefrontEvent_eventName_createdAt_idx" ON "StorefrontEvent" USING btree ("eventName", "createdAt");
CREATE INDEX "StorefrontEvent_source_createdAt_idx" ON "StorefrontEvent" USING btree (source, "createdAt");
CREATE UNIQUE INDEX "WaitlistEntry_email_key" ON "WaitlistEntry" USING btree (email);
CREATE UNIQUE INDEX session_token_key ON session USING btree (token);
CREATE UNIQUE INDEX user_email_key ON "user" USING btree (email);
