-- ======================================================================
-- Data — restore this AFTER 01-schema.sql
--
-- Generated by Polsia from your app database.
-- Source PostgreSQL : 16.15 (ef25dd3)
-- Source schema     : public
-- Snapshot taken at : 2026-09-08 19:17:40.627251+00
--
-- Foreign keys are added at the END of this file, once every row is in place,
-- so table and row order does not matter.
-- ======================================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET DateStyle = 'ISO, MDY';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';
SET search_path TO public;


-- Address

-- CheckoutOrder

-- DigitalPurchase

-- StorefrontEvent

-- waitlist_signups

-- account

-- contact_message

-- session

-- user

-- verification
-- Foreign keys — added last, so the rows above could load in any order.
ALTER TABLE account ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE session ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Give the planner statistics to work with.
ANALYZE;
